# Generated by Django 4.2.5 on 2023-10-05 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppPython', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiologia',
            name='fecha_turno',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dermatologia',
            name='fecha_turno',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='fecha_turno',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='odontologia',
            name='fecha_turno',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='oftalmologia',
            name='fecha_turno',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
