# Generated by Django 4.2.5 on 2023-10-05 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPython', '0002_cardiologia_fecha_turno_dermatologia_fecha_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiologia',
            name='dni',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.MaxLengthValidator(limit_value=12)]),
        ),
        migrations.AlterField(
            model_name='dermatologia',
            name='dni',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.MaxLengthValidator(limit_value=12)]),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='dni',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.MaxLengthValidator(limit_value=12)]),
        ),
        migrations.AlterField(
            model_name='odontologia',
            name='dni',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.MaxLengthValidator(limit_value=12)]),
        ),
        migrations.AlterField(
            model_name='oftalmologia',
            name='dni',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.MaxLengthValidator(limit_value=12)]),
        ),
    ]
