# Generated by Django 4.2.5 on 2023-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPython', '0004_cardiologia_especialidad_dermatologia_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiologia',
            name='especialidad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dermatologia',
            name='especialidad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='especialidad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='odontologia',
            name='especialidad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='oftalmologia',
            name='especialidad',
            field=models.CharField(default='', max_length=20),
        ),
    ]
